apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: techfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: techfood
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - name: sql-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: sql-scripts-volume
          configMap:
            name: techfood-configmap
            items:
              - key: schema.sql
                path: schema.sql
              - key: data-dev.sql
                path: data-dev.sql